version: "3.8"

services:
  elasticsearch:
    build:
      context: ./elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - mcp-network
    volumes:
      - ./esdata:/usr/share/elasticsearch/data

  mcp-api:
    build:
      context: ./mcp-api
    env_file:
      - ./mcp-api/.env.example
    ports:
      - "8000:8000"
    networks:
      - mcp-network
    depends_on:
      - elasticsearch

  crawler:
    build: ./crawler
    container_name: crawler
    volumes:
      - ./crawler_config:/app/crawler_config # クローラー設定ディレクトリをマウント
    depends_on:
      - elasticsearch
    environment:
      # ElasticsearchホストはDockerネットワーク名を使用
      - ES_HOST=elasticsearch
      - ES_PORT=9200
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
