version: "3.8"

services:
  elasticsearch:
    build:
      context: ./elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - mcp-network
    volumes:
      - ./esdata:/usr/share/elasticsearch/data

  mcp-api:
    build:
      context: ./mcp-api
    container_name: rag-mcp-api
    env_file:
      # - ./mcp-api/.env.sse
      - ./mcp-api/.env.streamable_http
    ports:
      - "8000:8000"
    environment:
      - ENABLE_EMBEDDING=${ENABLE_EMBEDDING:-false}
      - EMBEDDING_API_URL=http://embedding-api:8000/embed/text-embedding-3-small
    networks:
      - mcp-network
    depends_on:
      - elasticsearch
    
  chat-api:
    build:
      context: ./chat-api
    container_name: rag-chat-api
    ports:
      - "8080:8000" # ホスト側は8080でアクセス
    environment:
      - MCP_SERVER_URL=http://mcp-api:8000/mcp # mcp-apiへの内部URL
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LLM_MODEL=gpt-4o
      - ES_URL=http://elasticsearch:9200
    networks:
      - mcp-network
    depends_on:
      - mcp-api

  crawler:
    build: ./crawler
    container_name: crawler
    volumes:
      - ./crawler_config:/app/crawler_config # クローラー設定ディレクトリをマウント
    depends_on:
      - elasticsearch
    environment:
      # ElasticsearchホストはDockerネットワーク名を使用
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - CRAWLER_CONFIG_FILE=${CRAWLER_CONFIG_FILE:-crawler_config.yaml}
      - ENABLE_EMBEDDING=${ENABLE_EMBEDDING:-false}
      - EMBEDDING_API_URL=http://embedding-api:8000/embed/text-embedding-3-small
      - EMBEDDING_CHUNK_SIZE=2000
      - EMBEDDING_CHUNK_OVERLAP=100
    networks:
      - mcp-network
  
  embedding-api:
    profiles: ["embedding"]
    build:
      context: ./embedding-api
    container_name: rag-embedding-api
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY} # .envから読み込み
    ports:
      - "8001:8000" # ホストからは8001でアクセス
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
