start_urls:
  - https://fess.codelibs.org/ja/
allowed_domains:
  - fess.codelibs.org
target_url_patterns:
  - "https://fess.codelibs.org/ja/.*"
exclude_url_patterns:
  - "https://fess.codelibs.org/ja/archives.html"
max_depth: 50
delay: 0.5
user_agent: "MSFR Crawler/1.0"
es_index: "fess_ja_reference"
es_index_description: "Fess Japanese Reference Guide. Language: Japanese."
max_documents: 2000
embedding_chunk_size: 2000
embedding_chunk_overlap: 100
enable_embedding: true
